hooks:
  # Called when GitHub Actions triggers DevPanel webhook
  # Webhook payload includes: branch, sha, artifact_url
  git_hooks:
    push:
      - branch: "develop"
        cmd: |-
          /home/devpanel/applications/bonnici-digital/public_html/scripts/devpanel-deploy.sh develop "${DP_GIT_SHA:-unknown}" "${DP_ARTIFACT_URL:-}"

      - branch: "staging"
        cmd: |-
          /home/devpanel/applications/bonnici-digital/public_html/scripts/devpanel-deploy.sh staging "${DP_GIT_SHA:-unknown}" "${DP_ARTIFACT_URL:-}"

      - branch: "main"
        cmd: |-
          /var/www/html/scripts/devpanel-deploy.sh main "${DP_GIT_SHA:-unknown}" "${DP_ARTIFACT_URL:-}"

      - branch: "dripyard"
        cmd: |-
          composer -n install >> /tmp/composer_dripyard.txt
