hooks:
  # only called when $DP_TOKEN is setup in git provider
  # and git provider is set up to call the DevPanel git hook
  git_hooks:
    push:
      - branch: "main"
        cmd: |-
          composer -n install --no-dev >> /tmp/composer_main.txt
          drush cim -y
          drush cr
      - branch: "develop"
        cmd: |-
          composer -n install >> /tmp/composer_develop.txt
      - branch: "dripyard"
        cmd: |-
          composer -n install >> /tmp/composer_dripyard.txt
