_meta:
  version: '1.0'
  entity_type: node
  uuid: ceb9ed04-7405-4c11-9137-f237c0e140cb
  bundle: article
  default_langcode: en
  depends:
    07cd3f16-56b0-4418-95ac-6f23f5e132b3: file
    4e689e66-025a-4660-8519-2e9e0cd7f4bc: taxonomy_term
default:
  revision_uid:
    -
      target_id: 1
  status:
    -
      value: true
  uid:
    -
      target_id: 1
  title:
    -
      value: 'AI & Automation'
  created:
    -
      value: 1745291959
  promote:
    -
      value: true
  sticky:
    -
      value: false
  revision_translation_affected:
    -
      value: true
  path:
    -
      alias: ''
      langcode: en
  body:
    -
      value: "<p>NeonByte helps businesses unlock the full potential of AI by turning repetitive processes into intelligent, automated workflows. From data extraction and analysis to customer interactions and internal ops, we design AI-driven systems that learn, adapt, and scale with your needs. Our approach combines practical automation with real-world business logic — so you're not just saving time, you're making smarter decisions faster.</p><p>Whether you're integrating language models into your customer support, automating back-office tasks, or building predictive systems, NeonByte delivers solutions that are secure, explainable, and aligned with your goals. We believe AI should enhance your team, not replace it — and with the right strategy, it becomes a multiplier for your entire organization.</p>"
      format: full_html
      summary: ''
  field_image:
    -
      entity: 07cd3f16-56b0-4418-95ac-6f23f5e132b3
      alt: 'AI & Automation'
      title: ''
      width: 4464
      height: 3629
  field_tags:
    -
      entity: 4e689e66-025a-4660-8519-2e9e0cd7f4bc
