# Github
name: issue-greeter
on:
  push:
    branches:
      - dripyard
jobs:
  notify-devpanel-dripyard:
    runs-on: ubuntu-latest
    steps:
      - name: notify
        run: |
          curl -s -X PUT https://console.devpanel.com/webhooks/applications/6993669fbad55556203d3738/git -d "{\"username\": \"${{ secrets.DP_USERNAME }}\", \"token\": \"${{ secrets.DP_ACCESS_TOKEN }}\"}" -H "content-type: application/json"
          