# Github
name: issue-greeter
on:
  push:
    branches:
      - main
jobs:
  notify-devpanel-main:
    runs-on: ubuntu-latest
    steps:
      - name: notify
        run: |
          curl -s -X PUT https://console.devpanel.com/webhooks/applications/69883ed8b6432f91abfabe43/git -d "{\"username\": \"${{ secrets.DP_USERNAME }}\", \"token\": \"${{ secrets.DP_ACCESS_TOKEN }}\"}" -H "content-type: application/json"
